// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {SemaphoreDeployer} from "../../script/lib/SemaphoreDeployer.sol";
import {AidVault} from "../../src/funds/AidVault.sol";
import {IAidVault} from "../../src/interfaces/IAidVault.sol";
import {IDeliveryManager} from "../../src/interfaces/IDeliveryManager.sol";
import {INeedsRegistry} from "../../src/interfaces/INeedsRegistry.sol";
import {Errors} from "../../src/libraries/Errors.sol";
import {PoATest} from "../utils/PoATest.sol";
import {ISemaphore} from "@semaphore-protocol/contracts/interfaces/ISemaphore.sol";
import {ISemaphoreGroups} from "@semaphore-protocol/contracts/interfaces/ISemaphoreGroups.sol";

/// @notice Runs the delivery-confirmation path against **real Semaphore v4 contracts** with **real Groth16
///         proofs**, instead of the MockSemaphore used by the other suites.
/// @dev The proofs come from test/fixtures/semaphore-proofs.json, generated by `pnpm fixture:semaphore` inside
///      the contracts package. The fixture group is reproduced on-chain by adding the
///      same identity commitments in the same order, which yields the same Merkle root the proofs were made
///      against. Its scope is delivery id 1 — the first delivery opened in this test.
contract RealSemaphoreTest is PoATest, SemaphoreDeployer {
    uint256 internal constant TARGET = 5000e6;
    uint32 internal constant EXPECTED_RECIPIENTS = 5;

    address internal semaphoreAddress;
    address internal semaphoreVerifier;
    string internal fixture;

    uint256 internal fixtureRoot;
    uint256 internal fixtureScope;
    uint256 internal fixtureMessage;

    uint256 internal programId;
    uint256 internal needId;
    AidVault internal vault;

    function _setUpSemaphore() internal override returns (address) {
        (semaphoreAddress, semaphoreVerifier) = _deployLocalSemaphore();
        return semaphoreAddress;
    }

    function setUp() public override {
        super.setUp();

        fixture = vm.readFile("test/fixtures/semaphore-proofs.json");
        fixtureRoot = vm.parseJsonUint(fixture, ".merkleTreeRoot");
        fixtureScope = vm.parseJsonUint(fixture, ".scope");
        fixtureMessage = vm.parseJsonUint(fixture, ".message");

        // The fixture signs the same message the contract expects.
        assertEq(fixtureMessage, deliveryManager.AID_RECEIVED_MESSAGE(), "fixture message");

        // Program enrolled with the fixture's identity commitments, in fixture order.
        vm.prank(ngo);
        programId = groups.createProgram(POLICY_HASH, "ipfs://program");
        vm.prank(ngo);
        groups.addMembers(programId, vm.parseJsonUintArray(fixture, ".commitments"));

        // Need funded and pre-financed, so deliveries can start.
        needId = _createNeed(ngo, programId, TARGET, 1);
        _attestNeedVerified(verifier1, needId, true);
        vault = AidVault(registry.vaultOf(needId));
        _donate(donor1, needId, TARGET);
        vault.releaseTranche(0);
    }

    function _fixtureProof(uint256 index) internal view returns (ISemaphore.SemaphoreProof memory proof) {
        string memory key = string.concat(".proofs[", vm.toString(index), "]");
        uint256[] memory raw = vm.parseJsonUintArray(fixture, string.concat(key, ".points"));
        uint256[8] memory points;
        for (uint256 i; i < 8; ++i) {
            points[i] = raw[i];
        }
        proof = ISemaphore.SemaphoreProof({
            merkleTreeDepth: vm.parseJsonUint(fixture, string.concat(key, ".merkleTreeDepth")),
            merkleTreeRoot: fixtureRoot,
            nullifier: vm.parseJsonUint(fixture, string.concat(key, ".nullifier")),
            message: fixtureMessage,
            scope: fixtureScope,
            points: points
        });
    }

    function test_onChainGroupReproducesTheFixtureRoot() public view {
        uint256 groupId = groups.getGroupId(programId);
        assertEq(ISemaphoreGroups(semaphoreAddress).getMerkleTreeRoot(groupId), fixtureRoot, "merkle root");
        assertEq(ISemaphoreGroups(semaphoreAddress).getMerkleTreeSize(groupId), EXPECTED_RECIPIENTS, "size");
        assertEq(groups.memberCount(programId), EXPECTED_RECIPIENTS);
    }

    function test_realProofsUnlockTheNextTranche() public {
        vm.prank(fieldAgent);
        uint256 deliveryId = deliveryManager.openDelivery(needId, 1, EXPECTED_RECIPIENTS);
        assertEq(deliveryId, fixtureScope, "fixture scope must match the delivery id");
        _attestEvidence(fieldAgent, deliveryId);

        // 70% of 5 recipients = 4 confirmations, each a real zero-knowledge proof relayed by a third party.
        for (uint256 i; i < 4; ++i) {
            vm.prank(relayer);
            deliveryManager.confirmReceipt(deliveryId, _fixtureProof(i));
        }
        assertEq(deliveryManager.getDelivery(deliveryId).confirmations, 4);
        assertEq(deliveryManager.confirmationsNeeded(deliveryId), 0);
        assertEq(deliveryManager.getDelivery(deliveryId).status, IDeliveryManager.DeliveryStatus.Open);

        _attestDeliveryVerified(verifier2, deliveryId, true);
        assertEq(deliveryManager.getDelivery(deliveryId).status, IDeliveryManager.DeliveryStatus.Challengeable);

        vm.warp(block.timestamp + CHALLENGE_PERIOD);
        deliveryManager.finalize(deliveryId);
        assertEq(vault.trancheStatus(1), IAidVault.TrancheStatus.Releasable);

        vault.releaseTranche(1);
        assertEq(registry.statusOf(needId), INeedsRegistry.NeedStatus.InDelivery);
    }

    function test_realProofCannotBeReplayed() public {
        vm.prank(fieldAgent);
        uint256 deliveryId = deliveryManager.openDelivery(needId, 1, EXPECTED_RECIPIENTS);
        _attestEvidence(fieldAgent, deliveryId);

        vm.prank(relayer);
        deliveryManager.confirmReceipt(deliveryId, _fixtureProof(0));

        vm.prank(relayer);
        vm.expectRevert(ISemaphore.Semaphore__YouAreUsingTheSameNullifierTwice.selector);
        deliveryManager.confirmReceipt(deliveryId, _fixtureProof(0));

        assertEq(deliveryManager.getDelivery(deliveryId).confirmations, 1);
    }

    function test_tamperedProofIsRejected() public {
        vm.prank(fieldAgent);
        uint256 deliveryId = deliveryManager.openDelivery(needId, 1, EXPECTED_RECIPIENTS);
        _attestEvidence(fieldAgent, deliveryId);

        // Same nullifier and root, but the proof points were altered.
        ISemaphore.SemaphoreProof memory tampered = _fixtureProof(1);
        tampered.points[0] = tampered.points[0] ^ 1;
        vm.prank(relayer);
        vm.expectRevert(ISemaphore.Semaphore__InvalidProof.selector);
        deliveryManager.confirmReceipt(deliveryId, tampered);

        // A proof for a different group state (wrong root) is rejected too.
        ISemaphore.SemaphoreProof memory wrongRoot = _fixtureProof(1);
        wrongRoot.merkleTreeRoot = uint256(keccak256("not-the-group")) >> 8;
        vm.prank(relayer);
        vm.expectRevert(ISemaphore.Semaphore__MerkleTreeRootIsNotPartOfTheGroup.selector);
        deliveryManager.confirmReceipt(deliveryId, wrongRoot);

        assertEq(deliveryManager.getDelivery(deliveryId).confirmations, 0);
    }

    function test_proofForAnotherDeliveryIsRejected() public {
        vm.prank(fieldAgent);
        uint256 deliveryId = deliveryManager.openDelivery(needId, 1, EXPECTED_RECIPIENTS);
        _attestEvidence(fieldAgent, deliveryId);

        // The fixture is scoped to delivery 1; presenting it for another delivery fails the scope check,
        // and re-labelling the scope invalidates the proof itself.
        ISemaphore.SemaphoreProof memory relabelled = _fixtureProof(2);
        relabelled.scope = deliveryId + 1;
        vm.prank(relayer);
        vm.expectRevert(Errors.InvalidScope.selector);
        deliveryManager.confirmReceipt(deliveryId, relabelled);
    }

    /// @dev Right-to-erasure path: removing an identity changes the group root, and proofs made against the old
    ///      root stop working once Semaphore's root-validity window (1 hour by default) has passed.
    ///      Within that window an old proof is still accepted — a residual risk documented in the threat model.
    function test_removedMemberCannotConfirmAfterRootExpiry() public {
        vm.prank(fieldAgent);
        uint256 deliveryId = deliveryManager.openDelivery(needId, 1, EXPECTED_RECIPIENTS);
        _attestEvidence(fieldAgent, deliveryId);

        uint256 groupId = groups.getGroupId(programId);
        vm.prank(ngo);
        groups.removeMember(
            programId,
            vm.parseJsonUint(fixture, ".removal.commitment"),
            vm.parseJsonUintArray(fixture, ".removal.siblings")
        );

        assertEq(groups.memberCount(programId), EXPECTED_RECIPIENTS - 1, "member removed");
        assertEq(
            ISemaphoreGroups(semaphoreAddress).getMerkleTreeRoot(groupId),
            vm.parseJsonUint(fixture, ".removal.rootAfterRemoval"),
            "root changed"
        );

        // Still inside the root-validity window: an older proof is accepted by design.
        vm.prank(relayer);
        deliveryManager.confirmReceipt(deliveryId, _fixtureProof(0));
        assertEq(deliveryManager.getDelivery(deliveryId).confirmations, 1);

        // Past the window, proofs against the pre-removal root are rejected.
        vm.warp(block.timestamp + 2 hours);
        vm.prank(relayer);
        vm.expectRevert(ISemaphore.Semaphore__MerkleTreeRootIsExpired.selector);
        deliveryManager.confirmReceipt(deliveryId, _fixtureProof(4));
    }
}
