#!/usr/bin/env node
/**
 * Exports the ABIs the off-chain packages need into services/shared/src/abis/.
 *
 * Foundry artifacts are the source of truth for our own contracts; EAS ships its own compiled artifacts because
 * it pins a different solc version. The generated files are committed so `pnpm -r build` works on a clean clone
 * without running forge first.
 *
 *   pnpm abis
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(root, 'services', 'shared', 'src', 'abis')

const FORGE_ARTIFACTS = [
  'RoleRegistry',
  'NeedsRegistry',
  'AidVaultFactory',
  'AidVault',
  'NonCustodialLedger',
  'DonationReceipt',
  'BeneficiaryGroups',
  'DeliveryManager',
  'ProofOfAidResolver',
  'ConversionRouter',
  'DonationForwarder',
  'DonationForwarderFactory',
  'MockEURC',
  'MockYieldVault',
  'Semaphore',
]

const EAS_ARTIFACTS = {
  EAS: 'contracts/EAS.sol/EAS.json',
  SchemaRegistry: 'contracts/SchemaRegistry.sol/SchemaRegistry.json',
}

// "NeedsRegistry" -> "needsRegistry", "EAS" -> "eas" (acronyms stay readable)
const camel = (name) =>
  name === name.toUpperCase() ? name.toLowerCase() : name.charAt(0).toLowerCase() + name.slice(1)

const readForgeAbi = (name) => {
  const path = join(root, 'contracts', 'out', `${name}.sol`, `${name}.json`)
  return JSON.parse(readFileSync(path, 'utf8')).abi
}

const readEasAbi = (relative) => {
  const path = join(
    root,
    'contracts',
    'node_modules',
    '@ethereum-attestation-service',
    'eas-contracts',
    'artifacts',
    relative,
  )
  return JSON.parse(readFileSync(path, 'utf8')).abi
}

mkdirSync(outDir, { recursive: true })

const exports = []
const header = '// Generated by scripts/export-abis.mjs — do not edit by hand.\n'

for (const name of FORGE_ARTIFACTS) {
  const abi = readForgeAbi(name)
  const varName = `${camel(name)}Abi`
  writeFileSync(
    join(outDir, `${camel(name)}.ts`),
    `${header}export const ${varName} = ${JSON.stringify(abi)} as const\n`,
  )
  exports.push(`export { ${varName} } from './${camel(name)}.js'`)
}

for (const [name, relative] of Object.entries(EAS_ARTIFACTS)) {
  const abi = readEasAbi(relative)
  const varName = `${camel(name)}Abi`
  writeFileSync(
    join(outDir, `${camel(name)}.ts`),
    `${header}export const ${varName} = ${JSON.stringify(abi)} as const\n`,
  )
  exports.push(`export { ${varName} } from './${camel(name)}.js'`)
}

writeFileSync(join(outDir, 'index.ts'), `${header}${exports.join('\n')}\n`)
console.log(`wrote ${exports.length} ABIs to services/shared/src/abis/`)
